redesign the repo structure for the better professional environment
darkplayer0211/PresentationMaker pull request #3
Opened 2024-07-10 17:47 UTC by Mentoriassssssss

I have redesign the repository structure. The purpose is to make the repository more detailed, structured and organized.

2024-07-15 16:52 UTC, kietpt230 reviewed
I see some files are empty. Can you explain it for me, please ?

2024-07-15 16:52 UTC, kietpt230 commented on src/App.tsx
> +              console.log(Page)
Remove console.log, please

2024-07-15 16:56 UTC, kietpt230 requested changes

2024-07-15 16:56 UTC, kietpt230 commented on src/App.tsx
> +              console.log(Page)
Remove console.log, please

2024-07-15 16:56 UTC, kietpt230 commented on src/components/Header/header.tsx
> +export default Header;
Add end of line, please

2024-07-15 16:56 UTC, kietpt230 commented on src/components/Sidebar/sidebar.tsx
> +export default Sidebar;
Add end of line, please

2024-07-15 16:56 UTC, kietpt230 commented on src/layouts/defaultLayout/index.tsx
> +export default defaultLayout;
Add end of line, please

2024-07-15 16:56 UTC, kietpt230 commented on src/pages/following.tsx
> +export default Home;
Add end of line, please

2024-07-15 16:56 UTC, kietpt230 commented on src/pages/home.tsx
> +export default Home;
Add end of line, please

2024-07-15 16:56 UTC, kietpt230 commented on src/routes/index.tsx
> +export {publicRoutes, privateRoutes}
Add end of line, please

2024-07-15 16:58 UTC, kietpt230 commented
![image](https://github.com/user-attachments/assets/88d6d515-ce72-4167-a7c0-9d7beb347c5d)
Please, set the label correspond to the status of the PR

2024-07-16 17:37 UTC, darkplayer0211 commented
Hi @whbmc152,
cc @kietpt230,

Please support the idea of abstraction as discussed in the last Weekly Scrum.

You can add the **ProcessCore** folder in **components** and import it in **App.tsx**.

Or, you can separate the UI in the foreground with the **ui_src** folder and the processing in the background with the **process_src** folder.

Besides, please update the **README.md** file for the new folder structure too.

Best regards,
Tri Nguyen

2024-07-16 17:38 UTC, darkplayer0211 requested changes
Hi @whbmc152,
cc @kietpt230,

Please support the idea of abstraction as discussed in the last Weekly Scrum.

You can add the **ProcessCore** folder in **components** and import it in **App.tsx**.

Or, you can separate the UI in the foreground with the **ui_src** folder and the processing in the background with the **process_src** folder.

Besides, please update the **README.md** file for the new folder structure.

Best regards,
Tri Nguyen

2024-09-28 10:53 UTC, merged